(package-initialize)
(load "~/.emacs.d/load-directory")
(load "~/.emacs.d/use-package")
(load "~/.emacs.d/hl-line+")
(load-directory "~/.emacs.d/config")
(split-window-horizontally)
(other-window 1)
(split-window-vertically)
(balance-windows)
